language: java

sudo: required

branches:
  only:
  - master

services:
- docker

cache:
  directories:
  - docker
  - ~/.m2/repository


after_success:
- ./deployment/before-deploy.sh
- ./deployment/deploy.sh
